language: cpp

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - cmake

before_script:
  - pip3 install pep8
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make
  - make test
  