  language: cpp

addons:
  apt:
    packages:
      python3
      pip3

before_script:
  - pip3 install pep8
  - mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - make
  - ctest -V

matrix:
  include:
    - os: linux
      dist: precise
      addons:
        apt:
          sources:
            - sourceline: 'ppa:george-edison55/precise-backports'
          packages:
            - cmake
            - cmake-data
            - python3
            - pip3
    - os: linux
      dist: trusty